version: "3.9"

services:
  web:
    image: node
    container_name: web
    command: bash -c "npm install && npm run dev"
    working_dir: /app
    env_file:
      - ./.env
    ports:
      - ${WEB_PORT}:5173
    volumes:
      - ./web:/app
    networks:
      - deep_orange

  api:
    image: python-flask
    build: api
    container_name: api
    command: "uvicorn main:app --port ${API_PORT} --host 0.0.0.0 --reload"
    working_dir: /app
    env_file:
      - ./.env
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - ./api:/app
    networks:
      - deep_orange

  db:
    image: postgres
    container_name: db
    env_file:
      - ./.env
    ports:
      - ${DB_PORT}:5432
    volumes:
      - deep_orange_postgres:/var/lib/postgresql/data
    networks:
      - deep_orange

networks:
  deep_orange:

volumes:
  deep_orange_postgres: